project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"

book:
  title: "3rdSPDM"
  author: "JEBV"
  date: "04/11/2025"
  chapters:
    - index.qmd
    - 1_basics.qmd
    - 1_tbh.qmd
    - 2_grafeno.qmd
    - 3_haldane.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: united
      dark: slate
    toc: true
    toc-title: Contenido
    css: style.css
    code-fold: true
    code-summary: "Mostrar c√≥digo"
    code-line-numbers: true
    code-copy: true


